name: FANZA VR Auto Post (Stable)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"   # 6時間おき（UTC）

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run VR auto post
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
          DMM_API_ID: ${{ secrets.DMM_API_ID }}
          DMM_AFFILIATE_ID: ${{ secrets.DMM_AFFILIATE_ID }}
          CATEGORY: ${{ secrets.CATEGORY }}
          POST_LIMIT: "2"     # 1回で2本
          RECENT_DAYS: "3"    # 直近3日を“新作”扱い
          SCRAPE_DESC: "0"  # ← 安全運用なら0のまま推奨
          HITS: "30"
          MAX_PAGES: "6"
        run: python fanza_vr_auto_post.py
